### PR TITLE
col-sm-6 => too small for buttons

### PR DESCRIPTION
**Pull request by fgrosswig**
Changed the line into <div class="col-sm-10 align-items-stretch mb-3"> for allowing proper fit to the underlying buttons Update, Connect, Delete

### CODE REVIEW

**Comment by billz** [comment]
Hmm. Buttons with current `col-sm-6` on an iPhone SE. 

img

Changing the size to col-sm-10 breaks the grid layout on larger displays.

**Comment by fgrosswig** [comment]
> 
> 
> Hmm. Buttons with current `col-sm-6` on an iPhone SE.
> 
> img
> 
> Changing the size to col-sm-10 breaks the grid layout on larger displays.

I do agree you maintain it for mobile, but earlier versions had no issues with the buttons on mobile and desktop

**Comment by billz** [comment]
> earlier versions had no issues with the buttons on mobile and desktop

I guess I'm not clear on this. The current layout is responsive on mobile and desktop. This change breaks the latter

**Comment by fgrosswig** [comment]
ok ... i am closing the pull request and modify it on further upgrades manually.

**Pull request closed without merging**
