### PR TITLE
Adding cpu temperature

### PR DESCRIPTION
**Pull request by Weylin-fr**
I open the issue #478

i only modified those files :
- app/lib/system.php
- templates/system.php

### CODE REVIEW

**Comment by billz** [comment]
thanks :)

**Comment by Weylin-fr** [comment]
My first PR !
my pleasure :D

**Comment by pjkemp** [comment]
hows does one get access to the forks and the system  updates for use on a system?

**Comment by MomoSho** [comment]
Is it normal for the raspap/hostapd/servicestart.sh --interface to consume an entire CPU, 100% of the CPU the entire time it's running? I think this is causing my Pi to get very hot.
I'm using a Pi 3 B+ with Raspbian Buster 32 bit

**Comment by billz** [comment]
@MomoSho definitely not normal. which version of the project are you running?

**Comment by MomoSho** [comment]
@billz I'm using RaspAP v2.4. Would pulling an updated version help rectify this? I'm also running in managed AP mode.

**Comment by billz** [comment]
Unlikely. First time hearing of this CPU issue in a release version. The daemon is used to start up network services on boot when AP-STA or bridged mode is enabled. Assuming it's active, you can get some insights with:

```
ps aux | grep raspapd.service
sudo strace -p [pid]
```
where pid is the process ID of the service.

**Comment by MomoSho** [comment]
@billz the `/etc/raspap/hostapd/servicestart.sh --interface --seconds 3` never stops executing the entire time my pi is up (note raspap version 2.4). I tried installing the latest version (2.5) of raspap and the same issue persists. this process consumes 100% of a cpu the entire time it runs. Correct me if I’m wrong, but this script should end it’s execution upon completion of the boot up. So I end up having to kill it manually after the pi finishes booting and most everything seems fine. however my pi seems to kick connected devices off randomly after some time has passed regardless of this process’s execution state (but I’ll address this issue after fixing the 100% cpu load problem).

`systemctl status raspap.service` shows that this service is active (running). and `systemctl status raspapd.service` shows that this service is inactive (dead)`. Not sure what the difference is between `raspap.service` and `raspapd.service`.

I tried installing raspap 2.5 on a fresh install of Pi OS and this is no longer an issue. the command ends execution once the pi completes its boot up. I suspect something is hanging up the execution on my other pi setup and `raspapd.service` never actually starts. As far as I can tell there's only two loops within `servicestart.sh` to read the arguments and the config file. Additionally, all the services, `hostapd.services, dhcpcd.services, and dnsmasq.services` are all running. However, the dhcpcd states the warning: "the unit file, source configuration file or drop-ins of dhcpcd.service changed on disk. run ‘systemctl daemon-reload’ to reload units" and "wlan0 IAID conflicts with one assigned to uap0". I attempted `systemctl daemon-reload units`. And the issue still persists.
Is this hang up related to 
```
sed -i "s/\(--interface \)[[:alnum:]]*/\1$interface/" "$DAEMONPATH" 
```
mentioned earlier?

Not sure if this discussion/question falls under this thread. If I should post a formal issue/question please let me know. 

Do you have any further insights on this? I would like to know how to fix this issue without reinstalling a fresh version of pi os on my original pi. And without terminating the offending process on every reboot.

Thank you for your time.

**Comment by billz** [comment]
@MomoSho sounds like you have the old daemon (raspap.service) running in parallel with the updated one (raspap<ins>**d**</ins>.service). You can disable the former with `sudo systemctl disable raspap.service`.

**Comment by MomoSho** [comment]
@billz wow, thanks! looks like that did the trick. been wondering the difference between `systemctl stop` and `systemctl disable`. that service no longer runs on reboot. the cpu load is a lot happier. thanks again!

**Pull request merged**
