### PR TITLE
Mobile friendly Configure Client page

### PR DESCRIPTION
**Pull request by njkeng**
Ref Issue #168 
I have re-formatted the Configure Client page to work nicely with mobile device screen sizes.  I have kept all of the functionality of the original, but have placed everything in small-ish panels instead of a large table.

### CODE REVIEW

**Comment by randyoo** [comment]
I know the "priority" field was previously hidden, but I think that was due to the overflowing table on mobile devices. It would be really nice to expose it, or at least maintain the hidden fields for exposure later on...

**Comment by billz** [comment]
@njkeng there were several updates to the client UI around the time of this PR, and unfortunately the conflicts were never resolved. Good news is, I'm refactoring this now and will include your mobile friendly update.

**Comment by billz** [comment]
Refer to #261. Thanks

**Comment by billz** [comment]
Fixed in #168 and #261. Closing this PR. Thanks @njkeng.

**Pull request closed without merging**
