### PR TITLE
Bootstrap 4 / SB Admin 2 v4 update

### PR DESCRIPTION
**Pull request by billz**
See #413. Needs testing on modern browsers and mobile devices, including the project's included themes. The supported languages should also be spot checked for label wrapping, other UI issues.

### CODE REVIEW

**Comment by glaszig** [comment]
on mobile, the menu on the left is open by default. see below:

screenshot

**Comment by billz** [comment]
@glaszig noted, thanks! The sidebar still has a few todo items left:

- [ ]  collapse on mobile devices by default
- [ ]  persist collapsed/expanded state 
- [ ]  indicate selected nav item

plus a few other things I probably haven't thought of yet 😉

**Comment by billz** [comment]
This implements 2 sidebar toggles: 1) a topbar toggle for small devices (window size < 768), menu collapsed by default, and 2) a persistent sidebar toggle for larger devices (window size > 768). Both are adapted from SB Admin 2 

sidebars

**Comment by billz** [comment]
Tested and validated on the following:
- [ ] modern desktop browsers: Chrome, Firefox, Safari
- [ ]  mobile devices: iPhone 5s, Samsung Galaxy A30, iPad Mini

Worth noting that Bootstrap v4 dropped IE8, IE9, and iOS 6 support. v4 is now only IE10+ and iOS 7+

**Pull request merged**
