### PR TITLE
Customisable configuration

### PR DESCRIPTION
**Pull request by njkeng**
Ref #156
I have made quite a few changes allowing developers to quickly configure which parts of RaspAP they wish to use.  There are new flags and strings in config.php that control this functionality.  I have added two new items to the side menu for custom pages (which are disabled by default).  To go with these two new menu items, I have created two customizable pages as examples.
I have not yet edited README.md.  I wanted to see if you are happy with the code edits first.  If they're OK then I will add a "developer" section to README.md.

### CODE REVIEW

**Comment by glaszig** [comment]
what's the point of this? what's this custompage stuff?

**Comment by njkeng** [comment]
I have developed a dash camera for bicycles based on raspap. I used the two customisable pages for video settings and for video file management. Since I was developing these for my own purposes I thought I'd contribute in case others thought it was useful. 
Since I put in the pull request, raspap has had language support added. This makes the customisable pages a lot more complex since customisable strings would have to be added as well. This pull request is most likely impractical now.

**Comment by billz** [comment]
@njkeng your dash camera based on RaspAP sounds interesting. do you have a link to some documentation or photos of the project?

**Comment by njkeng** [comment]
@billz Here's full instructions for the keen DIYer
https://www.instructables.com/id/BikeCamera-Video-Camera/

**Pull request closed without merging**
